# GitHub Sponsors funding file
# This file configures the funding options for your repository

# GitHub sponsors username
# github: marcodroll

# Buy Me a Coffee
custom: ["https://www.buymeacoffee.com/nostramo"]

# Other funding platforms (uncomment and add usernames as needed)
# patreon: marcodroll
# ko_fi: marcodroll
# liberapay: marcodroll
# open_collective: creativewriter