version: '3.8'

services:
  nginx:
    image: ghcr.io/marcodroll/creativewriter2-nginx:latest
    container_name: creativewriter-nginx
    restart: unless-stopped
    ports:
      - "3080:80"  # Single port for both webapp and CouchDB
    depends_on:
      - creativewriter
      - couchdb
      - replicate-proxy
      - gemini-proxy
    networks:
      - creativewriter-network

  creativewriter:
    image: ghcr.io/marcodroll/creativewriter2:latest
    container_name: creativewriter
    restart: unless-stopped
    # No ports exposed directly - only through nginx
    environment:
      - TZ=Europe/Berlin  # Adjust timezone as needed
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - creativewriter-network
    depends_on:
      - couchdb

  couchdb:
    image: couchdb:3.3
    container_name: creativewriter-couchdb
    restart: unless-stopped
    # No ports exposed directly - only through nginx
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password  # Change this in production!
      - COUCHDB_SECRET=mysecret    # Change this in production!
    volumes:
      - /share/Docker/creativewriter/data/couchdb-data:/opt/couchdb/data
      - /share/Docker/creativewriter/data/log/couchdb_log:/opt/couchdb/var/log
    networks:
      - creativewriter-network

  replicate-proxy:
    image: ghcr.io/marcodroll/creativewriter2-proxy:latest
    container_name: creativewriter-replicate-proxy
    restart: unless-stopped
    environment:
      - REPLICATE_API_TOKEN=${REPLICATE_API_TOKEN}
      - PORT=3001
    networks:
      - creativewriter-network
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  gemini-proxy:
    image: ghcr.io/marcodroll/creativewriter2-gemini-proxy:latest
    container_name: creativewriter-gemini-proxy
    restart: unless-stopped
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - PORT=3002
    networks:
      - creativewriter-network
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  creativewriter-network:
    driver: bridge