name: Build and Push Proxy Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'proxy/**'
      - 'Dockerfile.proxy'
      - '.github/workflows/docker-proxy.yml'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-proxy

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version info
        id: version
        run: |
          # Get version from package.json and build number
          BUILD_NUMBER=${{ github.run_number }}
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          MAJOR_MINOR=$(echo $CURRENT_VERSION | cut -d. -f1-2)
          NEW_VERSION="${MAJOR_MINOR}.$BUILD_NUMBER"
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "Version: $NEW_VERSION"

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=v${{ steps.version.outputs.version }}
            type=raw,value=latest,enable={{is_default_branch}}
          labels: |
            org.opencontainers.image.title=${{ github.event.repository.name }}-proxy
            org.opencontainers.image.description=Proxy service for ${{ github.event.repository.name }}
            org.opencontainers.image.version=v${{ steps.version.outputs.version }}
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.proxy
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}