name: Sync to Public Repository

on:
  push:
    branches: [release]  # Only sync on release branch pushes
  workflow_dispatch: # Allow manual trigger

jobs:
  sync-public:
    runs-on: ubuntu-latest
    if: github.repository == 'MarcoDroll/creativewriter2' # Only run on private repo
    
    steps:
      - name: Checkout private repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Get full history
          token: ${{ secrets.PUBLIC_REPO_TOKEN }}

      - name: Setup Git and sync to public repository
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
          echo "Syncing release branch to public repository..."
          git remote add public https://x-access-token:${GITHUB_TOKEN}@github.com/MarcoDroll/creativewriter-public.git
          
          # Create a temporary branch without workflow files for public sync
          git checkout -b temp-public-sync
          git rm -r .github/ || true  # Remove workflow files
          git commit -m "Remove private workflow files for public sync" || true
          
          git push public temp-public-sync:main --force
          echo "✅ Successfully synced release branch to public repository main branch (without private workflows)"

      - name: Create release info
        run: |
          echo "Public repository updated at: $(date)"
          echo "Latest commit: $(git rev-parse --short HEAD)"
          echo "Commit message: $(git log -1 --pretty=%B)"